### ISSUE TITLE
Crash : AppUtils.java line 190  ,  euromsg.com.euromobileandroid.utils.AppUtils.carrier

### ISSUE THREAD

**Issue by muhammadalkhalaf** [relateddigital/euromessage-android#5]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at euromsg.com.euromobileandroid.utils.AppUtils.carrier(AppUtils.java:190)
       at euromsg.com.euromobileandroid.EuroMobileManager.saveSubscription(EuroMobileManager.java:263)
       at euromsg.com.euromobileandroid.EuroMobileManager.sync(EuroMobileManager.java:174)
       at euromsg.com.euromobileandroid.EuroMobileManager.subscribe(EuroMobileManager.java:164)
       at com.secretcv.android.fragment.HomeFragment1$3.onComplete(HomeFragment1.java:389)
       at com.google.android.gms.tasks.zzj.run(:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Please can you fix that !!

**Comment by relateddigital** [comment]
Hello, Can you check that you haven't provided Context as null?

**Comment by muhammadalkhalaf** [comment]
It is SDK file Read Only

**Comment by muhammadalkhalaf** [comment]
![image](https://user-images.githubusercontent.com/43862215/85273621-7e8cde80-b486-11ea-8bd8-fb682b333fb4.png)
I could not repeat the same bug , but Firebase Crashlytics shows 626 crashes

**Comment by relateddigital** [comment]
Hello, 
When you follow stack trace, you will see that you are passing context as null in "Subscribe Method" in Home Fragment. It seems that in some cases of your app produces Null Context,   Please check your Context. 

Best Regards :)

**Comment by muhammadalkhalaf** [comment]
I fixed it . Thank you
